#!/bin/bash
set -Eeuo pipefail

cd /usr/src

wget https://lx4u.ru/downloads/packages/flex-2.6.4.tar.gz
tar -xf flex-2.6.4.tar.gz
cd flex-2.6.4

./configure --prefix=/usr \
            --docdir=/usr/share/doc/flex \
            --disable-static

make
make install

ln -sv flex /usr/bin/lex
