#!/bin/bash
set -Eeuo pipefail
# Build package grub from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/grub-2.06.tar.xz
tar -xf grub-2.06.tar.xz
cd grub-2.06

unset {C,CPP,CXX,LD}FLAGS
./configure --prefix=/usr          \
            --sbindir=/sbin        \
            --sysconfdir=/etc      \
            --disable-efiemu       \
            --disable-werror
            
make
make install &&
mv -v /etc/bash_completion.d/grub /usr/share/bash-completion/completions
source /etc/profile
