#!/bin/bash
set -Eeuo pipefail
# Build package nano from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/nano-5.8.tar.xz
tar -xf nano-5.8.tar.xz
cd nano-5.8

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --enable-utf8
            
make
make install

dialog  --backtitle "Система портов Calmira Linux" --title " ASK " \
	--yesno "Установить документацию пакета nano?" 0 0

case $? in
	0)
		echo -e "\e[1mВыбрана установка документации...\e[0m"
		install -v -m644 doc/{nano.html,sample.nanorc} /usr/share/doc/nano
	;;
	
	1)
		echo -e "\e[1;31mУстановка документации НЕ выбрана\e[0m"
		exit 0
	;;
esac
