#!/bin/bash
# Build package util-macros from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://www.x.org/pub/individual/util/util-macros-1.19.3.tar.bz2
tar -xf util-macros-1.19.3.tar.bz2
cd util-macros-1.19.3

./configure $XORG_CONFIG
make install
