[package]
name         = "util-macros"
version      = "1.19.3"
description  = "The m4 macros used by all of the Xorg packages."
maintainer   = "Michail Krasnov <linuxoid85@gmail.com>"
releases     = ['v1.2a2', 'v1.2a3']
priority     = "user"
usage        = 0.632
upgrade_mode = "hard"
build_time   = 0.1

[deps]
required  = ["xorg/x11-minimal/XBE"]
recommend = []
optional  = []
conflict  = []

[port]
url  = "https://www.x.org/pub/individual/util/"
file = "util-macros-1.19.3.tar.bz2"
md5  = "4be6df7e6af52e28e13dc533244eb9d7"
