#!/bin/bash
set -Eeuo pipefail
# Build package expat from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/expat-2.4.1.tar.xz
tar -xf expat-2.4.1.tar.xz
cd expat-2.4.1

./configure --prefix=/usr    \
            --disable-static
            
make
make install

dialog  --backtitle "Система портов Calmira Linux" --title " ASK " \
	--yesno "Установить документацию пакета expat?" 0 0

case $? in
	0)
		echo -e "\e[1mВыбрана установка документации...\e[0m"
		install -v -m644 doc/*.{html,png,css} /usr/share/doc/expat
	;;
	
	1)
		echo -e "\e[1;31mУстановка документации НЕ была выбрана.\e[0m"
		exit 0
	;;
esac
