#!/bin/bash
set -Eeuo pipefail
# Build package libXdmcp from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://www.x.org/pub/individual/lib/libXdmcp-1.1.3.tar.bz2
tar -xf libXdmcp-1.1.3.tar.bz2
cd libXdmcp-1.1.3

./configure $XORG_CONFIG --docdir=/usr/share/doc/libXdmcp-1.1.3 &&
make
make install
