#!/bin/bash
set -Eeuo pipefail
# Build package mako from port
# Port created by Linuxoid85 <linuxoid85@gmail.com>
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="1.1.3" # Version of mako

wget https://files.pythonhosted.org/packages/source/M/Mako/Mako-$VERSION.tar.gz
tar -xf Mako-$VERSION.tar.gz
cd Mako-$VERSION

python3 setup.py install --optimize=1
package_add_port_db
