#!/bin/bash
set -Eeuo pipefail
# Build package MarkupSafe from port
# Port created by Linuxoid85 <linuxoid85@gmail.com>
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="1.1.1" # Version of MarkupSafe

wget https://files.pythonhosted.org/packages/source/M/MarkupSafe/MarkupSafe-$VERSION.tar.gz
tar -xf MarkupSafe-$VERSION.tar.gz
cd MarkupSafe-$VERSION

python2 setup.py build
python3 setup.py build

python2 setup.py install --optimize=1
python3 setup.py install --optimize=1

package_add_port_db
