#!/bin/bash
# Build package dialog from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget http://deb.debian.org/debian/pool/main/d/dialog/dialog_1.3-20201126.orig.tar.gz
tar -xf dialog_1.3-20201126.orig.tar.gz
cd dialog-1.3-20201126.orig.tar.gz

./configure --prefix=/usr --enable-nls --disable-rpatch-hack

make
make install
