#!/bin/bash
# Build package xbitmaps from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://www.x.org/pub/individual/data/xbitmaps-1.1.2.tar.bz2
tar -xf xbitmaps-1.1.2.tar.bz2
cd xbitmaps-1.1.2

./configure $XORG_CONFIG
make install
