#!/bin/bash
# Build package xcb-util-cursor from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://xcb.freedesktop.org/dist/xcb-util-cursor-0.1.3.tar.bz2
tar -xf xcb-util-cursor-0.1.3.tar.bz2
cd xcb-util-cursor-0.1.3

./configure $XORG_CONFIG &&
make
make install
