#!/bin/bash
# Build package libsecret from port
# Port created by Uknown author
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/lib/cpkg/other-functions.sh
cd /usr/src

VERSION="0.20.3" # Version of libsecret

wget http://ftp.gnome.org/pub/gnome/sources/libsecret/0.20/libsecret-$VERSION.tar.xz
tar -xf libsecret-$VERSION.tar.xz
cd libsecret-$VERSION

mkdir bld &&
cd bld &&

meson --prefix=/usr -Dgtk_doc=false .. &&
ninja

ninja install
