#!/bin/bash
#
# Скрипт для обновления портов в Calmira Linux
# (C) 2021 Linuxoid85 <linuxoid85@gmail.com>
#

source /etc/cpkg/system.version

cd /usr/ports

case $1 in
	stable)
		echo -e "\e[1mОбновление портов со стабильной ветки...\e[0m"
		git clone https://gitlab.com/Linuxoid85/calmira_ports
		mv calmira_ports /usr/ports
		
		cd /usr/ports
		rm -fv {update-ports,CHANGELOG,README.md,LICENSE,ports-lx4_1.0.txz}
	;;
	
	testing)
		echo -e "\e[1;31mНа данный момент тестовой ветки не существует.\e[0m"
		exit 1
	;;
esac
