#!/bin/bash
# Build package efivar from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/efivar-37.tar.bz2 https://raw.githubusercontent.com/Linux4Yourself/Linux4Yourself.Book.Packages/develop/patches/efivar-37-gcc_9-1.patch
tar -xf efivar-37.tar.bz2
cd efivar-37

patch -Np1 -i ../efivar-37-gcc_9-1.patch

make CFLAGS="-O2 -Wno-stringop-truncation"
make install LIBDIR=/usr/lib BINDIR=/usr/bin
