#!/bin/bash
set -Eeuo pipefail
# Build package libgudev from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://download.gnome.org/sources/libgudev/236/libgudev-236.tar.xz
tar -xf libgudev-236.tar.xz
cd libgudev-236

mkdir build &&
cd    build &&

meson --prefix=/usr --buildtype=release .. &&
ninja
ninja install
