#!/bin/bash
# Build package nasm from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/lib/cpkg/other-functions.sh
cd /usr/src

VERSION="2.15.03" # Version of nasm

wget http://www.nasm.us/pub/nasm/releasebuilds/2.15.03/nasm-$VERSION.tar.xz
tar -xf nash-$VERSION.tar.xz
cd nasm-$VERSION

./configure --prefix=/usr &&
make
make install

package_add_port_db
