#!/bin/bash
# Build package libksba from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://www.gnupg.org/ftp/gcrypt/libksba/libksba-1.6.0.tar.bz2
tar -xf libksba-1.6.0.tar.bz2
cd libksba-1.6.0

./configure --prefix=/usr &&
make
make install
