#!/bin/bash
# Build package less from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/less-581.2.tar.gz
tar -xf less-581.2.tar.gz
cd less-581.2

./configure --prefix=/usr --sysconfdir=/etc

make
make install
