#!/bin/bash
set -Eeuo pipefail
# Build package libtasn1 from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/libtasn1-4.17.0.tar.gz
tar -xf libtasn1-4.17.0.tar.gz
cd libtasn1-4.17.0

./configure --prefix=/usr --disable-static

make
make install
