#!/bin/bash
# Build package rest from port
# Port created by Uknown author
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/lib/cpkg/other-functions.sh
cd /usr/src

VERSION="0.8.1" # Version of rest

wget http://ftp.gnome.org/pub/gnome/sources/rest/0.8/rest-$VERSION.tar.xz
tar -xf rest-$VERSION.tar.xz
cd rest-$VERSION

./configure --prefix=/usr \
    --with-ca-certificates=/etc/pki/tls/certs/ca-bundle.crt &&
make
make install

package_add_port_db
