#!/bin/bash -e
# Build script for 'ntfs-3g' package
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="ntfs-3g_ntfsprogs"
VERSION="2021.8.22"

cd /usr/src/"$NAME-$VERSION"

echo -e "\a\e[1;31m--== WARNING ==--\e[0m"

cat << "EOF"
A new read-write driver for NTFS, called NTFS3, has been added into the Linux
kernel since the 5.15 release. The performance of NTFS3 is much better than
ntfs-3g. To enable NTFS3, enable the following options in the kernel
configuration and recompile the kernel if necessary:

    File systems  --->
      <*/M> NTFS Read-Write file system support [CONFIG_NTFS3_FS]

To ensure the mount command uses NTFS3 for ntfs partitions, create a wrapper
script '/sbin/mount.ntfs':

    #!/bin/sh
    # Begin /sbin/mount.ntfs
    exec mount -t ntfs3 "$@"
    # End /sbin/mount.ntfs

And run:
    chmod -v 755 /sbin/mount.ntfs

With the kernel support available, ntfs-3g is only needed if you need the
utilities from it (for example, to create NTFS filesystems).
EOF

echo -e -n "\e[1mPress <ENTER> key to continue...\e[0m"
read

echo -e "\a\e[1m--== WARNING ==--\e[0m"
cat << "EOF"
Enable the following options in the kernel configuration and recompile the
kernel if necessary:

    File systems  --->
      <*/M> FUSE (Filesystem in Userspace) support [CONFIG_FUSE_FS]
EOF

echo -e "\a"
sleep 3
echo -e "\a"

./configure --prefix=/usr        \
            --disable-static     \
            --with-fuse=internal \
            --docdir=/usr/share/doc/ntfs-3g-$VERSION

make
make install

ln -sv ../bin/ntfs-3g /sbin/mount.ntfs
ln -sv ntfs-3g.8 /usr/share/man/man8/mount.ntfs.8

echo -e "\a\e[1m--== NOTE ==--\e[0m"
cat << "EOF"
---=== USING nfts-3g PORT PACKAGE ===---

To mount a Windows partition at boot time, put a line like this in /etc/fstab:

    /dev/sda1 /mnt/windows auto defaults 0 0

To allow users to mount a usb stick with an NTFS filesystem on it, put a line
similar to this (change sdc1 to whatever a usb stick would be on your system) in
/etc/fstab:

            /dev/sdc1 /mnt/usb auto user,noauto,umask=0,utf8 0 0

In order for a user to be able to mount the usb stick, they will need to be able
to write to /mnt/usb, so as the root user:

    chmod -v 777 /mnt/usb
EOF
echo -e "\a"
