#!/bin/bash

cd /usr/src

VERSION="2.34"

wget https://ftp.gnu.org/gnu/glibc/glibc-$VERSION.tar.xz https://raw.githubusercontent.com/Linux4Yourself/Linux4Yourself.Book.Packages/develop/patches/glibc-$VERSION-fhs-1.patch https://www.iana.org/time-zones/repository/releases/tzdata2021a.tar.gz
tar -xf glibc-$VERSION.tar.xz
cd glibc-$VERSION

sed -e '/NOTIFY_REMOVED)/s/)/ \&\& data.attr != NULL)/' \
    -i sysdeps/unix/sysv/linux/mq_notify.c

patch -Np1 -i ../glibc-$VERSION-fhs-1.patch

mkdir  build
cd     build

echo "rootsbindir=/usr/sbin" > configparms

../configure                             \
      --prefix=/usr                      \
      --disable-werror                   \
      --enable-kernel=3.2                \
      --with-headers=/usr/include        \
      libc_cv_slibdir=/lib 

make

touch /etc/ld.so.conf
sed '/test-installation/s@$(PERL)@echo not running@' -i ../Makefile

make install
cp -v ../nscd/nscd.conf /etc/nscd.conf
mkdir -pv /var/cache/nscd

localedef -i POSIX -f UTF-8 C.UTF-8 2> /dev/null || true
localedef -i en_US -f UTF-8 en_US.UTF-8
localedef -i ru_RU -f UTF-8 ru_RU.UTF-8

ldconfig
