#!/bin/bash
set -Eeuo pipefail
cd /usr/src/WindowMaker-0.95.9

source ./port-configuration.sh # This port settings
# $PREFIX - the installation prefix
# $LANGS  - the supported languages (see './configure LINGUAS="list"' for more info)

./configure --prefix=$PREFIX --enable-usermenu LINGUAS="$LANGS"
make
make install
