#!/bin/bash
set -Eeuo pipefail
# Build package bootscripts (for SysVInit) from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://github.com/Linux4Yourself/bootscripts/releases/download/1.1/bootscripts.tar.xz

echo -e "\e[1mДанная версия пакета \e[0m\e[35mbootscripts\e[0m\e[1m оптимизирована для работы в системе с раздельной системой каталогов\e[0m"
tar -xvf bootscripts.tar.xz
cd bootscripts

make install
