#!/bin/bash
# Build package mc from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget http://ftp.midnight-commander.org/mc-4.8.25.tar.xz
tar -xf mc-4.8.25.tar.xz
cd mc-4.8.25

./configure --prefix=/usr \
            --sysconfdir=/etc \
            --enable-charset &&
make
make install
