#!/bin/bash
set -Eeuo pipefail
# Build package alsa-lib from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.5.1.tar.bz2
tar -xf alsa-lib-1.2.5.1.tar.bz2
cd alsa-lib-1.2.5.1

warn_dialog "Перед/после сборки этого порта ОБЯЗАТЕЛЬНО пересоберите ядро Linux!

Device Drivers --->
-> <*/M> Sound card support --->                  [CONFIG_SOUND]
--> <*/M> Advanced Linux Sound Architecture ---> [CONFIG_SND]
---> Select settings and drivers appropriate for your hardware."

./configure &&
make
make install
