#!/bin/bash
set -Eeuo pipefail
# Build package libXau from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://www.x.org/pub/individual/lib/libXau-1.0.9.tar.bz2
tar -xf libXau-1.0.9.tar.bz2
cd libXau-1.0.9

./configure $XORG_CONFIG &&
make
make install
