#!/bin/bash
# Build package python from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="3.10.0"

wget https://lx4u.ru/downloads/packages/Python-$VERSION.tar.xz
tar -xf Python-$VERSION.tar.xz
cd Python-$VERSION

./configure --prefix=/usr        \
            --enable-shared      \
            --with-system-expat  \
            --with-system-ffi    \
            --with-ensurepip=yes \
            --enable-optimizations

make
make installs
