#!/bin/bash
# Build package psmisc from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/psmisc-23.4.tar.xz
tar -xf psmisc-23.4.tar.xz
cd psmisc-23.4

./configure --prefix=/usr
make
make install
