#!/bin/bash
set -Eeuo pipefail
# Build package util-linux (for SysVInit) from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="2.37.2"

wget https://lx4u.ru/downloads/packages/util-linux-$VERSION.tar.xz
tar -xf util-linux-$VERSION.tar.xz
cd util-linux-$VERSION

./configure ADJTIME_PATH=/var/lib/hwclock/adjtime   \
            --disable-chfn-chsh  \
            --disable-login      \
            --disable-nologin    \
            --disable-su         \
            --disable-setpriv    \
            --disable-runuser    \
            --disable-pylibmount \
            --disable-static     \
            --without-python     \
            --without-systemd    \
            --without-systemdsystemunitdir \
            runstatedir=/run

make
make install