#!/bin/bash
# Build package npth from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://www.gnupg.org/ftp/gcrypt/npth/npth-1.6.tar.bz2
tar -xf npth-1.6.tar.bz2
cd npth-1.6

./configure --prefix=/usr &&
make
make install
