#!/bin/bash
# Build package sysklogd (for SysVInit) from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/sysklogd-1.5.1.tar.gz
tar -xf sysklogd-1.5.1.tar.gz
cd sysklogd-1.5.1

sed -i '/Error loading kernel symbols/{n;n;d}' ksym_mod.c
sed -i 's/union wait/int/' syslogd.c

make
make BINDIR=/sbin install

dialog  --backtitle "Система сборки Calmira Linux" --title " ASK " \
	--yesno "Выполнить настройку пакета? Если вы обновляете его до новой версии, переустанавливаете или вы уже создали/отредактировани нужные/уже существующие конфиги для sysklogd, то ответьте 'Нет', дабы не потерять свои настройки.
	
Если вы ответите 'Да', то Система Портов создаст стандартные конфиги. В том случае, если нужные файлы уже существуют, то они будут удалены и на их месте созданы новые со стандартным значением." 0 0

case $? in
	0)
		echo -e "\e[1mВыбрана настройка пакета...\e[0m"
		cat > /etc/syslog.conf << "EOF"
# Begin /etc/syslog.conf

auth,authpriv.* -/var/log/auth.log
*.*;auth,authpriv.none -/var/log/sys.log
daemon.* -/var/log/daemon.log
kern.* -/var/log/kern.log
mail.* -/var/log/mail.log
user.* -/var/log/user.log
*.emerg *

# End /etc/syslog.conf
EOF
	;;
	
	1)
		echo -e "\e[1;31mНастройка пакета НЕ была выбрана.\e[0m"
		exit 0
	;;
esac
