#!/bin/bash
# Build package libpipeline from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="1.5.4"

wget https://lx4u.ru/downloads/packages/libpipeline-$VERSION.tar.gz
tar -xf libpipeline-$VERSION.tar.gz
cd libpipeline-$VERSION

./configure --prefix=/usr

make
make install
