#!/bin/bash
# Build package docutils from port
# Port created by Linuxoid85 <linuxoid85@gmail.com>
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/lib/cpkg/other-functions.sh
cd /usr/src

VERSION="0.16" # Version of docutils

wget http://downloads.sourceforge.net/docutils/docutils-$VERSION.tar.gz
tar -xf docutils-$VERSION.tar.gz
cd docutils-$VERSION

python3 setup.py build
python3 setup.py install --optimize=1 &&

for f in /usr/bin/rst*.py; do
  ln -svf $(basename $f) /usr/bin/$(basename $f .py)
done

package_add_port_db
