#!/bin/bash
# Build package gdbm from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="1.22"

wget https://lx4u.ru/downloads/packages/gdbm-$VERSION.tar.gz
tar -xf gdbm-$VERSION.tar.gz
cd gdbm-$VERSION

./configure --prefix=/usr    \
            --disable-static \
            --enable-libgdbm-compat
            
make
make install
