#!/bin/bash
set -Eeuo pipefail
cd /usr/src/libuv-v1.41.0

# TODO: The sh autogen.sh command below fails if the ACLOCAL environment variable is set as specified in Xorg-7.
if [ -n $ACLOCAL ]; then
    unset ACLOCAL
fi

sh autogen.sh
./configure --prefix=/usr --disable-static
make

make install
