#!/bin/bash
set -Eeuo pipefail
# Build package tcsh from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget ftp://ftp.astron.com/pub/tcsh/tcsh-6.22.03.tar.gz
tar -xf tcsh-6.22.03.tar.gz
cd tcsh-6.22.03

./configure --prefix=/usr --bindir=/bin

make &&
sh ./tcsh.man2html

make install install.man &&

ln -v -sf tcsh   /bin/csh &&
ln -v -sf tcsh.1 /usr/share/man/man1/csh.1 &&

install -v -m755 -d          /usr/share/doc/tcsh-6.22.03/html &&
install -v -m644 tcsh.html/* /usr/share/doc/tcsh-6.22.03/html &&
install -v -m644 FAQ         /usr/share/doc/tcsh-6.22.03

if grep 'tcsh' /etc/shells; then
	echo "OK"
else
cat >> /etc/shells << "EOF"
/bin/tcsh
EOF
fi

if grep 'csh' /etc/shells; then
	echo "OK"
else
cat >> /etc/shells << "EOF"
/bin/csh
EOF
fi
