#!/bin/bash
# Build package xorgproto from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://xorg.freedesktop.org/archive/individual/proto/xorgproto-2020.1.tar.bz2
tar -xf xorgproto-2020.1.tar.bz2
cd xorgproto-2020.1

mkdir build &&
cd    build &&

meson --prefix=$XORG_PREFIX -Dlegacy=true .. &&
ninja

ninja install &&

install -vdm 755 $XORG_PREFIX/share/doc/xorgproto-2020.1 &&
install -vm 644 ../[^m]*.txt ../PM_spec $XORG_PREFIX/share/doc/xorgproto-2020.1
