#!/bin/bash
# Build package procps-ng (for SysVInit) from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/procps-ng-3.3.17.tar.xz
tar -xf procps-ng-3.3.17.tar.xz
cd procps-ng-3.3.17

./configure --prefix=/usr                            \
            --disable-static                         \
            --disable-kill
            
make
make install
