#!/bin/bash
# Build package procps-ng (for SysVInit) from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/procps-ng-3.3.17.tar.xz
tar -xf procps-ng-3.3.17.tar.xz
cd procps-3.3.17

./configure --prefix=/usr                            \
            --disable-static                         \
	        --exec-prefix=                           \
	        --libdir=/usr/lib                        \
            --disable-kill
            
make
make install

mv -v /usr/lib/libprocps.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libprocps.so) /usr/lib/libprocps.so

