#!/bin/bash
# Build package grep from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="3.7"

wget https://lx4u.ru/downloads/packages/grep-$VERSION.tar.xz
tar -xf grep-$VERSION.tar.xz
cd grep-$VERSION

./configure --prefix=/usr --bindir=/bin
make
make install
