#!/bin/bash
# Build package grep from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/grep-3.6.tar.xz
tar -xf grep-3.6.tar.xz
cd grep-3.6

./configure --prefix=/usr --bindir=/bin
make
make install
