[package]
name         = "libuv"
version      = "1.43.0"
description  = "The libuv package is a multi-platform support library with a focus on asynchronous I/O"
maintainer   = "Michail Krasnov <linuxoid85@gmail.com>"
releases     = ['v1.2a2', 'v1.2a3']
priority     = "system"
usage        = 14
upgrade_mode = "hard"
build_time   = 0.1

[deps]
required  = ["none"]

[build_deps]
required  = ["none"]

[port]
url  = "https://dist.libuv.org/dist/v1.43.0/"
file = "libuv-v1.43.0.tar.gz"
md5  = "2e2fd46f60ff73b17a04add5a934b2e9"
