#!/bin/bash
# Build package glib from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://download.gnome.org/sources/glib/2.68/glib-2.68.3.tar.xz https://www.linuxfromscratch.org/patches/blfs/svn/glib-2.68.3-skip_warnings-1.patch
tar -xf glib-2.68.3.tar.xz
cd glib-2.68.3

patch -Np1 -i ../glib-2.68.3-skip_warnings-1.patch
if [ -e /usr/include/glib-2.0 ]; then
    rm -rf /usr/include/glib-2.0.old &&
    mv -vf /usr/include/glib-2.0{,.old}
fi

mkdir build &&
cd    build &&

meson --prefix=/usr       \
      --buildtype=release \
      -Dman=true          \
      -Dselinux=disabled  \
      ..                  &&
ninja

ninja install &&

mkdir -p /usr/share/doc/glib-2.68.3 &&
cp -r ../docs/reference/{NEWS,gio,glib,gobject} /usr/share/doc/glib-2.68.3

rm -f /usr/include/glib-2.0/glib/gurifuncs.h
