#!/bin/bash
# Build package diffutils from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="3.8"

wget https://lx4u.ru/downloads/packages/diffutils-$VERSION.tar.xz
tar -xf diffutils-$VERSION.tar.xz
cd diffutils-$VERSION

./configure --prefix=/usr

make
make install
