#!/bin/bash
set -Eeuo pipefail
# Build package alsa-plugins from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://www.alsa-project.org/files/pub/plugins/alsa-plugins-1.2.5.tar.bz2
tar -xf alsa-plugins-1.2.5.tar.bz2
cd alsa-plugins-1.2.5

./configure --sysconfdir=/etc &&
make
make install
