#!/bin/bash
# Build package ncurses from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/ncurses-6.2.tar.gz
tar -xf ncurses-6.2.tar.gz
cd ncurses-6.2

./configure --prefix=/usr           \
            --mandir=/usr/share/man \
            --with-shared           \
            --without-debug         \
            --without-normal        \
            --enable-pc-files       \
            --enable-widec          \
            --with-pkg-config-libdir=/usr/lib/pkgconfig
            
make
make install

mv -v /usr/lib/libncursesw.so.6* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libncursesw.so) /usr/lib/libncursesw.so

for lib in ncurses form panel menu ; do
    rm -vf                    /usr/lib/lib${lib}.so
    echo "INPUT(-l${lib}w)" > /usr/lib/lib${lib}.so
    ln -sfv ${lib}w.pc        /usr/lib/pkgconfig/${lib}.pc
done

rm -vf                     /usr/lib/libcursesw.so
echo "INPUT(-lncursesw)" > /usr/lib/libcursesw.so
ln -sfv libncurses.so      /usr/lib/libcurses.so

rm -fv /usr/lib/libncurses++w.a

dialog  --backtitle "Система портов Calmira Linux" --title " ASK " \
	--yesno "Для запуска старых программ требуется библиотека ncurses без широких символов. Создать её?" 0 0

case $? in
	0)
		echo -e "\e[1mКомпилируется ncurses без широких символов...\e[0m"
		make distclean
		./configure --prefix=/usr    \
		            --with-shared    \
		            --without-normal \
		            --without-debug  \
		            --without-cxx-binding \
		            --with-abi-version=5
		make sources libs
		cp -av lib/lib*.so.5* /usr/lib
	;;
	
	1)
		echo -e "\e[31mКомпиляция ncurses без широких символов не выбрана.\e[0m"
		exit 0
	;;
esac
