#!/bin/bash
set -Eeuo pipefail
# Build package DHCP from port
# Port created by Uknown author
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="4.4.2" # Version of DHCP

wget ftp://ftp.isc.org/isc/dhcp/$VERSION/dhcp-$VERSION.tar.gz
tar -xf dhcp-$VERSION.tar.gz
cd dhcp-$VERSION

print_ps_msg "NOTE" " You must have Packet Socket support. IPv6 support is optional. You can rebuild the kernel after building this port.

[*] Networking support --->        [CONFIG_NET]
 Networking options --->
  <*> Packet socket          [CONFIG_PACKET]
  <*> The IPv6 Protocol ---> [CONFIG_IPV6]"

sed -i '/o.*dhcp_type/d' server/mdb.c &&
sed -r '/u.*(local|remote)_port/d'    \
    -i client/dhclient.c              \
       relay/dhcrelay.c

( export CFLAGS="$CFLAGS -Wall -fno-strict-aliasing                 \
        -D_PATH_DHCLIENT_SCRIPT='\"/sbin/dhclient-script\"'         \
        -D_PATH_DHCPD_CONF='\"/etc/dhcp/dhcpd.conf\"'               \
        -D_PATH_DHCLIENT_CONF='\"/etc/dhcp/dhclient.conf\"'"        &&

./configure --prefix=/usr                                           \
            --sysconfdir=/etc/dhcp                                  \
            --localstatedir=/var                                    \
            --with-srv-lease-file=/var/lib/dhcpd/dhcpd.leases       \
            --with-srv6-lease-file=/var/lib/dhcpd/dhcpd6.leases     \
            --with-cli-lease-file=/var/lib/dhclient/dhclient.leases \
            --with-cli6-lease-file=/var/lib/dhclient/dhclient6.leases
) &&
make -j1

make install                   &&
mv -v /usr/sbin/dhclient /sbin &&
install -v -m755 client/scripts/linux /sbin/dhclient-script

package_add_port_db

print_ps_msg "WARNING" "Для настройки DHCP вы должны установить сервис '/lib/services/dhcpcd' из calm-bootscripts. Об установке 'calm-bootscripts' читайте в файле 'setup.html' из директории с этим портом."

print_ps_msg "NOTE" "Вы должны САМИ настроить/создать конфигурационные файлы '/etc/sysconfig/ifconfig.eth0' и '/etc/resolv.conf{,.head}' для правильной работы DHCP-$VERSION. О настройке смотрите в файле 'setup.html' из директории с этим портом."
