#!/bin/bash -e
# Build script for 'dosfstools' package
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="dosfstools"
VERSION="4.2"

cd /usr/src/"$NAME-$VERSION"

echo -e "\a\e[1m--== WARNING ==--\e[0m"

cat << "EOF"
Enable the following option in the kernel configuration and recompile the
kernel:

    File systems --->
      <DOS/FAT/EXFAT/NT Filesystems --->
        <*/M> MSDOS fs support             [CONFIG_MSDOS_FS]
        <*/M> VFAT (Windows-95) fs support [CONFIG_VFAT_FS]
EOF

echo -e "\a"
sleep 3
echo -e "\a"

./configure --prefix=/usr            \
            --enable-compat-symlinks \
            --mandir=/usr/share/man  \
            --docdir=/usr/share/doc/dosfstools-$VERSION

make
make install
