[package]
name         = "dosfstools"
version      = "4.2"
description  = "The dosfstools package contains various utilities for use with the FAT family of file systems."
maintainer   = "Michail Krasnov <linuxoid85@gmail.com>"
releases     = ['v1.2a2', 'v1.2a3']
priority     = "user"
usage        = 3.5
upgrade_mode = "hard"
build_time   = 0.07

[deps]
required  = []
recommend = []
optional  = []
conflict  = []

[build_deps]
required  = []
recommend = []

[port]
url  = "https://github.com/dosfstools/dosfstools/releases/download/v4.2/"
file = "dosfstools-4.2.tar.gz"
md5  = "49c8e457327dc61efab5b115a27b087a"
