#!/bin/bash
# Build package wget from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/wget-1.21.1.tar.gz
tar -xf wget-1.21.1.tar.gz
cd wget-1.21.1

dialog  --backtitle "Система портов Calmira Linux" --title " WARNING " \
	--msgbox "Советуется установить пакет make-ca, если он ещё не установлен. Он требуется для корректной работы wget и некоторых других пакетов." 0 0

./configure --prefix=/usr --sysconfdir=/etc \
            --with-ssl=openssl
            
make
make install
