#!/bin/bash
# Build package gcr from port
# Port created by Uknown author
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/lib/cpkg/other-functions.sh
cd /usr/src

VERSION="3.36.0" # Version of gcr

wget http://ftp.gnome.org/pub/gnome/sources/gcr/3.36/gcr-$VERSION.tar.xz
tar -xf gcr-$VERSION.tar.xz
cd gcr-$VERSION

warn_dialog "If you are upgrading from a version of gcr prior to 3.36.0, you must run the remove-la-files.sh script from the Libtool archive (.la) files after installing gcr."

sed -i -r 's:"(/desktop):"/org/gnome\1:' schema/*.xml &&

sed -i '610 s/;/ = { 0 };/' gck/gck-slot.c &&

mkdir gcr-build &&
cd    gcr-build &&

meson --prefix=/usr -Dgtk_doc=false .. &&
ninja

ninja install

package_add_port_db
