#!/bin/bash
# Build package efibootmgr from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/efibootmgr-17.tar.gz
tar -xf efibootmgr-17.tar.gz
cd efibootmgr-17

sed -e '/extern int efi_set_verbose/d' -i src/efibootmgr.c

make EFIDIR=LIN EFI_LOADER=grubx64.efi
make install sbindir=/usr/bin EFIDIR=LIN
