#!/bin/bash
# Build package gzip from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="1.11"

wget https://lx4u.ru/downloads/packages/gzip-$VERSION.tar.xz
tar -xf gzip-$VERSION.tar.xz
cd gzip-$VERSION

./configure --prefix=/usr

make
make install

mv -v /usr/bin/gzip /bin
