#!/bin/bash
# Build package check from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/check-0.15.2.tar.gz
tar -xf check-0.15.2.tar.gz
cd check-0.15.2

./configure --prefix=/usr
make
make docdir=/usr/share/doc/check install
