#!/bin/bash
set -Eeuo pipefail
# Build package gperf from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/gperf-3.1.tar.gz
tar -xf gperf-3.1.tar.gz
cd gperf-3.1

./configure --prefix=/usr
make
make install
