#!/bin/bash
# Build package grub from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/grub-2.06.tar.xz https://unifoundry.com/pub/unifont/unifont-13.0.06/font-builds/unifont-13.0.06.pcf.gz
tar -xf grub-2.06.tar.xz
cd grub-2.06

mkdir -pv /usr/share/fonts/unifont &&
gunzip -c unifont-13.0.06.pcf.gz > /usr/share/fonts/unifont/unifont.pcf

unset {C,CPP,CXX,LD}FLAGS
./configure --prefix=/usr        \
            --sbindir=/usr/bin      \
            --sysconfdir=/etc    \
            --disable-efiemu     \
            --enable-grub-mkfont \
            --with-platform=efi  \
            --disable-werror
            
make
make install &&
mv -v /etc/bash_completion.d/grub /usr/share/bash-completion/completions
source /etc/profile
