#!/bin/bash
set -Eeuo pipefail

cd /usr/src

VERSION="20211004"

wget https://lx4u.ru/downloads/packages/iana-etc-$VERSION.tar.gz
tar -xvf iana-etc-$VERSION.tar.gz
cd iana-etc-$VERSION

cp services protocols /etc
