NAME=glib
VERSION=2.64.4
DESCRIPTION="The GLib package contains low-level libraries useful for providing data structure handling for C, portability wrappers and interfaces for such runtime functionality as an event loop, threads, dynamic loading and an object system."
SITE="http://ftp.gnome.org/pub/gnome/sources/glib"
RECOM_DEPS="libxlst-1.1.34 PCRE-8.44"
OPT_DEPS="dbus-1.12.20 bindfs (both may be used in some tests) GDB-9.2 (for bindings) docbook-xml-4.5 docbook-xsl-1.79.2 GTK-Doc-1.32 (to build API documentation)"
MAINTAINER=Linuxoid85
PORT="true"
PRIORITY=user
FILES="/usr/share/gdb/auto-load/usr/lib/libglib-2.0.so.0.6400.4-gdb.py
/usr/share/gdb/auto-load/usr/lib/libgobject-2.0.so.0.6400.4-gdb.py
/usr/share/aclocal/glib-gettext.m4
/usr/share/aclocal/gsettings.m4
/usr/share/aclocal/glib-2.0.m4
/usr/share/locale/ru/LC_MESSAGES/glib20.mo
/usr/share/locale/en@shaw/LC_MESSAGES/glib20.mo
/usr/share/locale/en_CA/LC_MESSAGES/glib20.mo
/usr/share/locale/en_GB/LC_MESSAGES/glib20.mo
/usr/share/bash-completion/completions/gresource
/usr/share/bash-completion/completions/gsettings
/usr/share/bash-completion/completions/gdbus
/usr/share/bash-completion/completions/gapplication
/usr/share/bash-completion/completions/gio
/usr/share/gettext/its/gschema.its
/usr/share/gettext/its/gschema.loc
/usr/share/glib-2.0/gdb/glib_gdb.py
/usr/share/glib-2.0/gdb/gobject_gdb.py
/usr/share/glib-2.0/valgrind/glib.supp
/usr/share/glib-2.0/gettext/po/Makefile.in.in
/usr/share/glib-2.0/schemas/gschema.dtd
/usr/share/glib-2.0/codegen/utils.py
/usr/share/glib-2.0/codegen/__init__.py
/usr/share/glib-2.0/codegen/codegen_docbook.py
/usr/share/glib-2.0/codegen/parser.py
/usr/share/glib-2.0/codegen/config.py
/usr/share/glib-2.0/codegen/codegen.py
/usr/share/glib-2.0/codegen/dbustypes.py
/usr/share/glib-2.0/codegen/codegen_main.py
/usr/lib/libgobject-2.0.so.0
/usr/lib/libglib-2.0.so
/usr/lib/libgobject-2.0.so.0.6400.4
/usr/lib/libgobject-2.0.so
/usr/lib/pkgconfig/gobject-2.0.pc
/usr/lib/pkgconfig/gmodule-2.0.pc
/usr/lib/pkgconfig/gmodule-export-2.0.pc
/usr/lib/pkgconfig/gmodule-no-export-2.0.pc
/usr/lib/pkgconfig/glib-2.0.pc
/usr/lib/pkgconfig/gio-2.0.pc
/usr/lib/pkgconfig/gthread-2.0.pc
/usr/lib/pkgconfig/gio-unix-2.0.pc
/usr/lib/libgio-2.0.so.0.6400.4
/usr/lib/libgio-2.0.so
/usr/lib/libgmodule-2.0.so.0
/usr/lib/libglib-2.0.so.0
/usr/lib/libgthread-2.0.so
/usr/lib/libgthread-2.0.so.0.6400.4
/usr/lib/libgio-2.0.so.0
/usr/lib/libglib-2.0.so.0.6400.4
/usr/lib/libgmodule-2.0.so
/usr/lib/glib-2.0
/usr/bin/gresource
/usr/bin/gtester-report
/usr/bin/glib-gettextize
/usr/bin/gsettings
/usr/bin/glib-genmarshal
/usr/bin/glib-compile-resources
/usr/bin/gio-querymodules
/usr/bin/glib-mkenums
/usr/bin/gdbus
/usr/bin/gapplication
/usr/bin/gtester
/usr/bin/gio
/usr/bin/gobject-query
/usr/bin/gdbus-codegen
/usr/bin/glib-compile-schemas
/usr/include/gio-unix-2.0/gio/gunixcredentialsmessage.h
/usr/include/gio-unix-2.0/gio/gunixconnection.h
/usr/include/gio-unix-2.0/gio/gunixinputstream.h
/usr/include/gio-unix-2.0/gio/gunixoutputstream.h
/usr/include/gio-unix-2.0/gio/gunixmounts.h
/usr/include/gio-unix-2.0/gio/gfiledescriptorbased.h
/usr/include/gio-unix-2.0/gio/gunixfdmessage.h
/usr/include/gio-unix-2.0/gio/gunixsocketaddress.h
/usr/include/gio-unix-2.0/gio/gdesktopappinfo.h
/usr/include/gio-unix-2.0/gio/gunixfdlist.h
/usr/include/glib-2.0"
