#!/bin/bash
# Build package glib from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget http://ftp.gnome.org/pub/gnome/sources/glib/2.64/glib-2.64.4.tar.xz
tar -xf glib-2.64.4.tar.xz
cd glib-2.64.4

patch -Np1 -i ../glib-2.64.4-skip_warnings-1.patch
mkdir build &&
cd    build &&

meson --prefix=/usr      \
      -Dman=true         \
      -Dselinux=disabled \
      ..                
ninja

ninja install &&

mkdir -p /usr/share/doc/glib-2.64.4 &&
cp -r ../docs/reference/{NEWS,gio,glib,gobject} /usr/share/doc/glib-2.64.4
