#!/bin/bash
set -Eeuo pipefail
# Build package openssl from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="3.0.0"

wget https://lx4u.ru/downloads/packages/openssl-$VERSION.tar.gz
tar -xf openssl-$VERSION.tar.gz
cd openssl-$VERSION

./config --prefix=/usr         \
         --openssldir=/etc/ssl \
         --libdir=lib          \
         shared                \
         zlib-dynamic

make
sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile
make MANSUFFIX=ssl install
