#!/bin/bash -e
# Build script for 'cracklib' package
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

NAME="cracklib"
VERSION="2.9.7"

cd /usr/src/"$NAME-$VERSION"

wget https://github.com/cracklib/cracklib/releases/download/v2.9.7/$NAME-words-$VERSION.bz2
sed -i '/skipping/d' util/packer.c
sed -i '15209 s/.*/am_cv_python_version=3.10/' configure

PYTHON=python3 CPPFLAGS=-I/usr/include/python3.10 \
./configure --prefix=/usr    \
            --disable-static \
            --with-default-dict=/usr/lib/cracklib/pw_dict
make
make install

install -v -m644 -D    ../cracklib-words-2.9.7.bz2 \
                         /usr/share/dict/cracklib-words.bz2    &&

bunzip2 -v               /usr/share/dict/cracklib-words.bz2    &&
ln -v -sf cracklib-words /usr/share/dict/words                 &&
echo $(hostname) >>      /usr/share/dict/cracklib-extra-words  &&
install -v -m755 -d      /usr/lib/cracklib                     &&

create-cracklib-dict     /usr/share/dict/cracklib-words \
                         /usr/share/dict/cracklib-extra-words
