#!/bin/bash
# Build package bison from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/bison-3.7.6.tar.xz
tar -xf bison-3.7.6.tar.xz
cd bison-3.7.6

./configure --prefix=/usr --docdir=/usr/share/doc/bison

make
make install
