#!/bin/bash
# Build package fluxbox from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://downloads.sourceforge.net/fluxbox/fluxbox-1.3.7.tar.xz
tar -xf fluxbox-1.3.7.tar.xz
cd fluxbox-1.3.7

./configure --prefix=/usr &&
make
make install

echo startfluxbox > ~/.xinitrc

if [ $SETUP = true ]; then
	mkdir -pv /usr/share/xsessions &&
cat > /usr/share/xsessions/fluxbox.desktop << "EOF"
[Desktop Entry]
Encoding=UTF-8
Name=Fluxbox
Comment=This session logs you into Fluxbox
Exec=startfluxbox
Type=Application
EOF
	mkdir -v ~/.fluxbox &&
	cp -v /usr/share/fluxbox/init ~/.fluxbox/init &&
	cp -v /usr/share/fluxbox/keys ~/.fluxbox/keys
	cp -v /usr/share/fluxbox/menu ~/.fluxbox/menu
fi

