#!/bin/bash
set -Eeuo pipefail

cd /usr/src

wget https://lx4u.ru/downloads/packages/zstd-1.5.0.tar.gz
tar -xf zstd-1.5.0.tar.gz
cd zstd-1.5.0

make
make prefix=/usr install
rm -v /usr/lib/libzstd.a

mv -v /usr/lib/libzstd.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libzstd.so) /usr/lib/libzstd.so
