#!/bin/bash
# Build package attr from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/attr-2.5.1.tar.gz
tar -xf attr-2.5.1.tar.gz
cd attr-2.5.1

./configure --prefix=/usr    \
            --disable-static \
            --sysconfdir=/etc
            
make
make install
