#!/bin/bash -e
# Build script for 'XBS' port
# Copyright (C) 2022 Michail Krasnov <linuxoid85@gmail.com>

source /usr/ports/xorg/x11-minimal/XBE/port-configuration.sh

# VARIABLES IN 'port-configuration.sh' FILE:
# XORG_PREFIX - the Xorg installation prefix (default = "/opt/X11")
# BUILD_KDE - for create symlink for KDE (default: "NO", other: "YES")

export XORG_CONFIG="--prefix=$XORG_PREFIX --sysconfdir=/etc \
    --localstatedir=/var --disable-static"

cat > /etc/profile.d/xorg.sh << EOF
XORG_PREFIX="$XORG_PREFIX"
XORG_CONFIG="--prefix=\$XORG_PREFIX --sysconfdir=/etc --localstatedir=/var --disable-static"
export XORG_PREFIX XORG_CONFIG
EOF
chmod 644 /etc/profile.d/xorg.sh

cat >> /etc/profile.d/xorg.sh << "EOF"

pathappend $XORG_PREFIX/bin             PATH
pathappend $XORG_PREFIX/lib/pkgconfig   PKG_CONFIG_PATH
pathappend $XORG_PREFIX/share/pkgconfig PKG_CONFIG_PATH

pathappend $XORG_PREFIX/lib             LIBRARY_PATH
pathappend $XORG_PREFIX/include         C_INCLUDE_PATH
pathappend $XORG_PREFIX/include         CPLUS_INCLUDE_PATH

ACLOCAL="aclocal -I $XORG_PREFIX/share/aclocal"

export PATH PKG_CONFIG_PATH ACLOCAL LIBRARY_PATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH
EOF

source /etc/profile.d/xorg.sh

echo "$XORG_PREFIX/lib" >> /etc/ld.so.conf
sed "s@/usr/X11R6@$XORG_PREFIX@g" -i /etc/man_db.conf

ln -svf $XORG_PREFIX/share/X11 /usr/share/X11

if [ "$BUILD_KDE" -eq "YES" ]; then
    ln -svf $XORG_PREFIX /usr/X11R6
fi
