#!/bin/bash

cd /usr/src

VERSION="5.1.1"

wget https://lx4u.ru/downloads/packages/bc-$VERSION.tar.xz
tar -xf bc-$VERSION.tar.xz
cd bc-$VERSION

CC=gcc ./configure --prefix=/usr -G -O3
make
make install
