#!/bin/bash
# Build package tree from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget http://mama.indstate.edu/users/ice/tree/src/tree-1.8.0.tgz
tar -xf tree-1.8.0.tgz
cd tree-1.8.0

make
make MANDIR=/usr/share/man/man1 install &&
chmod -v 644 /usr/share/man/man1/tree.1
