#!/bin/bash
set -Eeuo pipefail
# Build package popt from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/popt-1.18.tar.gz
tar -xf popt-1.18.tar.gz
cd popt-1.18

./configure --prefix=/usr    \
            --disable-static
            
make
make install
