#!/bin/bash
set -Eeuo pipefail
# Build package xcb-util-image from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://xcb.freedesktop.org/dist/xcb-util-image-0.4.0.tar.bz2
tar -xf xcb-util-image-0.4.0.tar.bz2
cd xcb-util-image-0.4.0

./configure $XORG_CONFIG &&
make
make install
