#!/bin/bash
# Build package mpc from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/mpc-1.2.1.tar.gz
tar -xf mpc-1.2.1.tar.gz
cd mpc-1.2.1

./configure --prefix=/usr        \
            --disable-static
            
make
make install
