#!/bin/bash
set -Eeuo pipefail
source /usr/libexec/cport.sh
cd /usr/src/fcron-3.2.1.src

echo -e -n ">>> \e[1;31m Does you installed this package before? (y/n): \e[0m"
read run

if [[ $run == "Y" ]] || [[ $run == "y" ]]; then
	echo "OK"
else
	cat >> /etc/syslog.conf << "EOF"
# Begin fcron additional to /etc/syslog.conf

cron.* -/var/log/cron.log

# End fcron addition
EOF

echo "Restarting the 'sysklogd' daemon..."
/etc/rc.d/init.d/sysklogd reload
fi

groupadd -g 22 fcron
useradd -d /dev/null -c "Fcron user" -g fcron -s /bin/false -u 22 fcron

# NOTE:
# Если вы устанавливали что-то из MTA, то можете заменить опцию 
# '--without-sendmail' на '--with-sendmail=</путь/до/программы/MTA>'

./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var \
	--without-sendmail --with-boot-install=no --with-systemdsystemunitdir=no

make
make install

note_msg "\e[1mConfiguration files:\e[0m
 * /etc/fcron.conf
 * /etc/fcron.allow
 * /etc/fcron.deny"

warning_msg "Для того, чтобы порт 'general/fcron' работал, вы должны установить
его сервис 'fcron' из \e[1mдополнительных\e[0m загрузочных скриптов!

# make install-fcron"

note_msg "\e[1mЗапуск fcron и генерация '/var/spool/fcron/systab':\e[0m
/etc/rc.d/init.d/fcron start &&
fcrontab -z -u systab"
