#!/bin/bash
# Build package meson from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="0.60.1"

wget https://lx4u.ru/downloads/packages/meson-$VERSION.tar.gz
tar -xf meson-$VERSION.tar.gz
cd meson-$VERSION

sed -i "s/return 'lib64'/return 'lib'/g" mesonbuild/mesonlib/universal.py

python3 setup.py build

python3 setup.py install --root=dest
cp -rv dest/* /
install -vDm644 data/shell-completions/bash/meson /usr/share/bash-completion/completions/meson
install -vDm644 data/shell-completions/zsh/_meson /usr/share/zsh/site-functions/_meson
