#!/bin/bash
set -Eeuo pipefail

cd /usr/src

VERSION="2.0.5"

wget https://lx4u.ru/downloads/packages/zlib-ng-$VERSION.tar.gz
tar -xf zlib-ng-$VERSION.tar.gz
cd zlib-ng-$VERSION

./configure --prefix=/usr --zlib-compat --native
make
make install
rm -fv /usr/lib/libz.a

mv -v /usr/lib/libz.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libz.so) /usr/lib/libz.so
