#!/bin/bash
# Build package wpa_supplicant from port
# Port created by Uknown author
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/lib/cpkg/other-functions.sh
cd /usr/src

VERSION="2.9" # Version of wpa_supplicant

wget https://w1.fi/releases/wpa_supplicant-$VERSION.tar.gz
tar -xf wpa_supplicant-$VERSION.tar.gz
cd wpa_supplicant-$VERSION

print_ps_msg "NOTE" "Enable the following options in the kernel configuration as well as specific device drivers for your hardware and recompile the kernel if necessary:

[*] Networking support  --->                              [CONFIG_NET]
 [*] Wireless  --->                                      [CONFIG_WIRELESS]
  <*/M> cfg80211 - wireless configuration API           [CONFIG_CFG80211]
   [*]     cfg80211 wireless extensions compatibility    [CONFIG_CFG80211_WEXT]
   <*/M> Generic IEEE 802.11 Networking Stack (mac80211) [CONFIG_MAC80211]
Device Drivers  --->
 [*] Network device support  --->                        [CONFIG_NETDEVICES]
   [*] Wireless LAN  --->                                [CONFIG_WLAN]"
print_ps_msg "NOTE" "Open the submenu and select the options that support your hardware: lspci from '/base/pciutils' port can be used to view your hardware configuration."

cat > wpa_supplicant/.config << "EOF"
CONFIG_BACKEND=file
CONFIG_CTRL_IFACE=y
CONFIG_DEBUG_FILE=y
CONFIG_DEBUG_SYSLOG=y
CONFIG_DEBUG_SYSLOG_FACILITY=LOG_DAEMON
CONFIG_DRIVER_NL80211=y
CONFIG_DRIVER_WEXT=y
CONFIG_DRIVER_WIRED=y
CONFIG_EAP_GTC=y
CONFIG_EAP_LEAP=y
CONFIG_EAP_MD5=y
CONFIG_EAP_MSCHAPV2=y
CONFIG_EAP_OTP=y
CONFIG_EAP_PEAP=y
CONFIG_EAP_TLS=y
CONFIG_EAP_TTLS=y
CONFIG_IEEE8021X_EAPOL=y
CONFIG_IPV6=y
CONFIG_LIBNL32=y
CONFIG_PEERKEY=y
CONFIG_PKCS12=y
CONFIG_READLINE=y
CONFIG_SMARTCARD=y
CONFIG_WPS=y
CFLAGS += -I/usr/include/libnl3
EOF

dialog --backtitle "Система портов Calmira GNU/Linux" --title " ASK " --yesno "Do you use NetworkManager, dbus and libxml2?" 0 0

case $? in
	1)
		echo "NO"
	;;

	0)
		echo "YES"
		touch /tmp/PORTS
		cat >> wpa_supplicant/.config << "EOF"
CONFIG_CTRL_IFACE_DBUS=y
CONFIG_CTRL_IFACE_DBUS_NEW=y
CONFIG_CTRL_IFACE_DBUS_INTRO=y
EOF
	;;
esac

cd wpa_supplicant &&
make BINDIR=/sbin LIBDIR=/lib

install -v -m755 wpa_{cli,passphrase,supplicant} /sbin/ &&
install -v -m644 doc/docbook/wpa_supplicant.conf.5 /usr/share/man/man5/ &&
install -v -m644 doc/docbook/wpa_{cli,passphrase,supplicant}.8 /usr/share/man/man8/

if [ -f "/tmp/PORTS" ]; then
	install -v -m644 dbus/fi.w1.wpa_supplicant1.service \
                 /usr/share/dbus-1/system-services/ &&
	install -v -d -m755 /etc/dbus-1/system.d &&
	install -v -m644 dbus/dbus-wpa_supplicant.conf \
                 /etc/dbus-1/system.d/wpa_supplicant.conf
fi

print_ps_msg "NOTE" "Вы должны САМИ настроить/создать конфигурационные файлы для правильной работы wpa_supplicant-$VERSION. О настройке смотрите в файле 'setup.html' из директории с этим портом."
