#!/bin/bash
# Build package which-orig from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://ftp.gnu.org/gnu/which/which-2.21.tar.gz
tar -xf which-2.21.tar.gz
cd which-2.21

./configure --prefix=/usr &&
make
make install
