#!/bin/bash
set -Eeuo pipefail
# Build package automake from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="1.16.5"

wget https://lx4u.ru/downloads/packages/automake-$VERSION.tar.xz
tar -xf automake-$VERSION.tar.xz
cd automake-$VERSION

sed -i "s/''/etags/" t/tags-lisp-space.sh
./configure --prefix=/usr

make
make install
