#!/bin/bash
set -Eeuo pipefail
# Build package libffi from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/libffi-3.4.2.tar.gz
tar -xf libffi-3.4.2.tar.gz
cd libffi-3.4.2

dialog  --backtitle "Система портов Calmira Linux" --title " WARNING " \
	--msgbox "Libffi как и GMP оптимизируется под определённый процессор. Если планируется переносить систему на компьютер с другим ЦП, экспортируйте CFLAGS и CXXFLAGS перед сборкой этого порта, чтобы указать универсальную сборку для вашей архитектуры." 0 0

./configure --prefix=/usr --disable-static --with-gcc-arch=native

make
make install
