#!/bin/bash
# Build package bootscripts (for SysVInit) from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/bootscripts.tar.xz
tar -xf bootscripts.tar.xz
cd bootscripts

make install
