#!/bin/bash
set -Eeuo pipefail
# Build package libuv from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://dist.libuv.org/dist/v1.41.0/libuv-v1.41.0.tar.gz
tar -xf libuv-v1.41.0.tar.gz
cd libuv-v1.41.0

unset ACLOCAL
sh autogen.sh                              &&
./configure --prefix=/usr --disable-static &&
make 
make install
