#!/bin/bash
# Build package unrar from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://www.rarlab.com/rar/unrarsrc-6.0.7.tar.gz
tar -xf unrarsrc-6.0.7.tar.gz
cd unrar

make -f makefile
install -v -m755 unrar /usr/bin
