#!/bin/bash
# Build package mesa from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://mesa.freedesktop.org/archive/mesa-20.3.4.tar.xz http://www.linuxfromscratch.org/patches/blfs/10.1/mesa-20.3.4-add_xdemos-1.patch
tar -xf mesa-20.3.4.tar.xz
cd mesa-20.3.4

patch -Np1 -i ../mesa-20.3.4-add_xdemos-1.patch
sed '1s/python/&3/' -i bin/symbols-check.py
GALLIUM_DRV="i915,iris,nouveau,r600,radeonsi,svga,swrast,virgl"
DRI_DRIVERS=""

mkdir build &&
cd    build &&

meson --prefix=$XORG_PREFIX          \
      -Dbuildtype=release            \
      -Ddri-drivers=$DRI_DRIVERS     \
      -Dgallium-drivers=$GALLIUM_DRV \
      -Dgallium-nine=false           \
      -Dglx=dri                      \
      -Dosmesa=gallium               \
      -Dvalgrind=disabled            \
      -Dlibunwind=disabled           \
      ..                             &&

unset GALLIUM_DRV DRI_DRIVERS &&

ninja
ninja install
