#!/bin/bash
# Build package diffutils from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/diffutils-3.7.tar.xz
tar -xf diffutils-3.7.tar.xz
cd diffutils-3.7

./configure --prefix=/usr

make
make install
