#!/bin/bash
# Build package gmp from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/gmp-6.2.1.tar.xz
tar -xf gmp-6.2.1.tar.xz
cd gmp-6.2.1

cp -v configfsf.guess config.guess
cp -v configfsf.sub config.sub

dialog --backtitle "Система портов Calmira Linux" --title " WARNING " --clear \
       --msgbox "Код gmp сильно оптимизирован для процессора, на котором построен. Изредка, если Calmira была перенесена на ПК с другим процессором, при компиляции она может выдавать ошибки 'Illegal instruction' и прерывать сборку программы." 0 0

dialog --backtitle "Система портов Calmira Linux" --title " WARNING " --clear \
       --yesno "Скомпилировать gmp с оптимизацией к процессору или нет? Если выбрать вариант 'Да', то gmp будет собран как обычно, но тогда возникнут проблемы с переносом системы на другой ПК. Если выбрать вариант 'Нет', то gmp будет собран БЕЗ привязки к текущему железу ПК. В таком случае, Calmira будет работать на всех совместимых ПК и вы сможете переносить систему на них без проблем." 0 0
       
case $? in
	0)
		dialog --backtitle "Система портов Calmira Linux" --title " WARNING " --clear \
			--msgbox "Была выбрана сборка с привязкой к процессору." 0 0
		
		./configure --prefix=/usr    \
                            --disable-static   --enable-cxx
	;;
	
	1)
		dialog --backtitle "Система портов Calmira Linux" --title " WARNING " --clear \
			--msgbox "Была выбрана сборка БЕЗ привязки к процессору." 0 0
		
		./configure --prefix=/usr    \
                            --disable-static   --enable-cxx --build=x86_64-pc-linux-gnu
	;;
	
	255)
		dialog --backtitle "Система портов Calmira Linux" --title " ERROR " --clear \
			--msgbox "Была нажата клавиша ESC. Сборка прервана." 0 0
		exit 0
	;;
esac

make
make install
