#!/bin/bash
set -Eeuo pipefail
# Build package gpm from port
# Port created by Uknown author
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION=1.20.7 # Version of gpm

wget http://anduin.linuxfromscratch.org/BLFS/gpm/gpm-$VERSION.tar.bz2 http://www.linuxfromscratch.org/patches/blfs/10.0/gpm-$VERSION-consolidated-1.patch
tar -xf gpm-$VERSION.tar.bz2
cd gpm-$VERSION

warn_dialog "Enable the following option in the kernel configuration and recompile the kernel if necessary:

Device Drivers  --->
 Input device support ---> [CONFIG_INPUT]
   <*/M> Mouse interface   [CONFIG_INPUT_MOUSEDEV]"

patch -Np1 -i ../gpm-1.20.7-consolidated-1.patch &&
./autogen.sh                                     &&
./configure --prefix=/usr --sysconfdir=/etc      &&
make

make install                                          &&

install-info --dir-file=/usr/share/info/dir           \
             /usr/share/info/gpm.info                 &&

ln -sfv libgpm.so.2.1.0 /usr/lib/libgpm.so            &&
install -v -m644 conf/gpm-root.conf /etc              &&

install -v -m755 -d /usr/share/doc/gpm-$VERSION/support &&
install -v -m644    doc/support/*                     \
                    /usr/share/doc/gpm-$VERSION/support &&
install -v -m644    doc/{FAQ,HACK_GPM,README*}        \
                    /usr/share/doc/gpm-$VERSION

package_add_port_db

print_ps_msg "NOTE" "Вы должны САМИ настроить/создать конфигурационные файлы для правильной работы gpm-$VERSION. О настройке смотрите в файле 'setup.html' из директории с этим портом."
