#!/bin/bash
set -Eeuo pipefail
# Build package usbutils from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://www.kernel.org/pub/linux/utils/usb/usbutils/usbutils-013.tar.xz
tar -xf usbutils-013.tar.xz
cd usbutils-013

./autogen.sh --prefix=/usr --datadir=/usr/share/hwdata &&
make
make install

install -dm755 /usr/share/hwdata/ &&
wget http://www.linux-usb.org/usb.ids -O /usr/share/hwdata/usb.ids

if [ ! -d "/etc/cron.weekly" ]; then
	mkdir -v /etc/cron.weekly
fi
cat > /etc/cron.weekly/update-usbids.sh << "EOF" &&
#!/bin/bash
set -Eeuo pipefail
/usr/bin/wget http://www.linux-usb.org/usb.ids -O /usr/share/hwdata/usb.ids
EOF
chmod 754 /etc/cron.weekly/update-usbids.sh
