#!/bin/bash
set -Eeuo pipefail
# Build package libtool from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/libtool-2.4.6.tar.xz
tar -xf libtool-2.4.6.tar.xz
cd libtool-2.4.6

./configure --prefix=/usr
make
make install
rm -fv /usr/lib/libltdl.a
