#!/bin/bash
# Build package gnupg from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-2.2.28.tar.bz2
tar -xf gnupg-2.2.28.tar.bz2
cd gnupg-2.2.28

sed -e '/noinst_SCRIPTS = gpg-zip/c sbin_SCRIPTS += gpg-zip' \
    -i tools/Makefile.in
sed -e '737a #if USE_LDAP' \
    -e '760a #endif' \
    -i dirmngr/dirmngr.c
./configure --prefix=/usr            \
            --localstatedir=/var     \
            --docdir=/usr/share/doc/gnupg-2.2.28
            
make &&

makeinfo --html --no-split -o doc/gnupg_nochunks.html doc/gnupg.texi &&
makeinfo --plaintext       -o doc/gnupg.txt           doc/gnupg.texi &&
make -C doc html

make install &&

install -v -m755 -d /usr/share/doc/gnupg-2.2.28/html            &&
install -v -m644    doc/gnupg_nochunks.html \
                    /usr/share/doc/gnupg-2.2.28/html/gnupg.html &&
install -v -m644    doc/*.texi doc/gnupg.txt \
                    /usr/share/doc/gnupg-2.2.28 &&
install -v -m644    doc/gnupg.html/* \
                    /usr/share/doc/gnupg-2.2.28/html
