#!/bin/bash
# Build package gawk from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/gawk-5.1.0.tar.xz
tar -xf gawk-5.1.0.tar.xz
cd gawk-5.1.0

sed -i 's/extras//' Makefile.in
./configure --prefix=/usr

make
make install

dialog  --backtitle "Система портов Calmira Linux" --title " ASK " \
	--yesno "Установить документацию пакета gawk?"

case $? in
	0)
		echo -e "\e[1mВыбрана установка документации...\e[0m"
		mkdir -v /usr/share/doc/gawk
		cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk
	;;
	
	1)
		echo -e "\e[1;31mУстановка документации НЕ выбрана.\e[0m"
		exit 0
	;;
esac
