#!/bin/bash -e
# Build script for 'which_script' package
# Copyright (C) 2021, 2022 Michail Krasnov <linuxoid85@gmail.com>

cat > /usr/bin/which << "EOF"
#!/bin/bash
type -pa "$@" | head -n 1 ; exit ${PIPESTATUS[0]}
EOF
chmod -v 755 /usr/bin/which
chown -v root:root /usr/bin/which
