[package]
name         = "which_script"
version      = "0.1"
description  = "shows the full path of (shell) commands installed in your PATH"
maintainer   = "Michail Krasnov <linuxoid85@gmail.com>"
releases     = ['v1.2a2', 'v1.2a3']
priority     = "user"
usage        = 0.1
upgrade_mode = "hard"
build_time   = 0.01

[deps]
required  = ["base/bash"]

[build_deps]
required  = ["base/bash"]

[port]
url  = "none"
file = "none"
md5  = "none"
