#!/bin/bash
set -Eeuo pipefail
# Build package patch from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/patch-2.7.6.tar.xz
tar -xf patch-2.7.6.tar.xz
cd patch-2.7.6

./configure --prefix=/usr

make
make install
