#!/bin/bash
# Build package libdrm from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/lib/cpkg/other-functions.sh
cd /usr/src

VERSION="2.4.102" # Version of libdrm

wget https://dri.freedesktop.org/libdrm/libdrm-$VERSION.tar.xz
tar -xf libdrm-$VERSION.tar.xz
cd libdrm-$VERSION

mkdir build &&
cd    build &&

meson --prefix=$XORG_PREFIX -Dudev=true &&
ninja
ninja install

package_add_port_db
