#!/bin/bash
set -Eeuo pipefail
# Build package xdg-user-dirs from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://user-dirs.freedesktop.org/releases/xdg-user-dirs-0.17.tar.gz
tar -xf xdg-user-dirs-0.17.tar.gz
cd xdg-user-dirs-0.17

./configure --prefix=/usr --sysconfdir=/etc &&
make
make install
