#!/bin/bash
set -Eeuo pipefail
# Build package bash from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/bash-5.1.8.tar.gz
tar -xf bash-5.1.8.tar.gz
cd bash-5.1.8

sed -i  '/^bashline.o:.*shmbchar.h/a bashline.o: ${DEFDIR}/builtext.h' Makefile.in
./configure --prefix=/usr                    \
            --without-bash-malloc            \
            --with-installed-readline
            
make
make install

mv -vf /usr/bin/bash /bin

sleep 1
dialog  --backtitle "Система портов Calmira Linux" --title " ASK " \
	--yesno "Если интерпретатор скомпилирован успешно, вам советуется запустить новую сессию bash с ним. Запустить?" 0 0

case $? in
	0)
		echo -e "\e[1mНовая сессия bash запускается...\e[0m"
		exec /bin/bash --login +h
	;;
	
	1)
		echo -e "\e[31mНовая сессия bash не будет запущена!\e[0m"
		exit 0
	;;
	
	255)
		echo -e "\e[31mБыла нажата клавиша ESC. Выход из порта...\e[0m"
		exit 1
	;;
esac
