#!/bin/bash
set -Eeuo pipefail
# Build package alsa-firmware from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

source /usr/share/ports/core-functions.sh
cd /usr/src

wget https://www.alsa-project.org/files/pub/firmware/alsa-firmware-1.2.4.tar.bz2
tar -xf alsa-firmware-1.2.4.tar.bz2
cd alsa-firmware-1.2.4

./configure --prefix=/usr &&
make
make install
