#!/bin/bash
# Build package intltool from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/intltool-0.51.0.tar.gz
tar -xf intltool-0.51.0.tar.gz
cd intltool-0.51.0

sed -i 's:\\\${:\\\$\\{:' intltool-update.in
./configure --prefix=/usr

make
make install

dialog  --backtitle "Система портов Calmira Linux" --title " ASK " \
	--yesno "Установить документацию пакета intltool?" 0 0

case $? in
	0)
		echo -e "\e[1mВыбрана установка документации...\e[0m"
		install -v -Dm644 doc/I18N-HOWTO /usr/share/doc/intltool/I18N-HOWTO
	;;
	
	1)
		echo -e "\e[1mУстановка документации НЕ выбрана.\e[0m"
		exit 0
	;;
esac
