#!/bin/bash
set -Eeuo pipefail
# Build package pciutils from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://www.kernel.org/pub/software/utils/pciutils/pciutils-3.7.0.tar.xz
tar -xf pciutils-3.7.0.tar.xz
cd pciutils-3.7.0

make PREFIX=/usr                \
     SHAREDIR=/usr/share/hwdata \
     SHARED=yes
     
make PREFIX=/usr                \
     SHAREDIR=/usr/share/hwdata \
     SHARED=yes                 \
     install install-lib        &&

chmod -v 755 /usr/lib/libpci.so

cat > /etc/cron.weekly/update-pciids.sh << "EOF" &&
#!/bin/bash
set -Eeuo pipefail
/usr/sbin/update-pciids
EOF
chmod 754 /etc/cron.weekly/update-pciids.sh
