#!/bin/bash
set -Eeuo pipefail
# Build package isl from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/isl-0.24.tar.xz
tar -xf isl-0.24.tar.xz
cd isl-0.24

./configure --prefix=/usr        \
            --disable-static 
            
make
make install
mkdir -pv /usr/share/gdb/auto-load/usr/lib
mv -v /usr/lib/libisl*gdb.py /usr/share/gdb/auto-load/usr/lib
