#!/bin/bash
set -Eeuo pipefail
# Build package inetutils from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="2.2"

wget https://lx4u.ru/downloads/packages/inetutils-$VERSION.tar.xz
tar -xf inetutils-$VERSION.tar.xz
cd inetutils-$VERSION

./configure --prefix=/usr        \
            --localstatedir=/var \
            --disable-logger     \
            --disable-whois      \
            --disable-rcp        \
            --disable-rexec      \
            --disable-rlogin     \
            --disable-rsh        \
            --disable-servers
            
make
make install

mv -v /usr/bin/{hostname,ping,ping6,traceroute} /bin
mv -v /usr/bin/ifconfig /sbin
