#!/bin/bash
set -Eeuo pipefail
# Build package gettext from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

wget https://lx4u.ru/downloads/packages/gettext-0.21.tar.xz
tar -xf gettext-0.21.tar.xz
cd gettext-0.21

./configure --prefix=/usr    \
            --disable-static
            
make
make install
chmod -v 0755 /usr/lib/preloadable_libintl.so
