#!/bin/bash
set -Eeuo pipefail
# Build package gcc from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

$VERSION="11.2.0"

wget https://lx4u.ru/downloads/packages/gcc-$VERSION.tar.xz
tar -xf gcc-$VERSION.tar.xz
cd gcc-$VERSION

sed -e '/m64=/s/lib64/lib/' \
    -e '/m32=/s/m32=.*/m32=..\/lib32$(call if_multiarch,:i386-linux-gnu)/' \
    -i.orig gcc/config/i386/t-linux64
    
mkdir -v build
cd       build
../configure --prefix=/usr               \
             LD=ld                       \
             --disable-bootstrap         \
             --with-system-zlib          \
             --enable-languages=c,c++  --disable-multilib

make
make install

rm -rf /usr/lib/gcc/$(gcc -dumpmachine)/$VERSION/include-fixed/bits/

chown -v -R root:root \
    /usr/lib/gcc/*linux-gnu/$VERSION/include{,-fixed}
    
ln -svr /usr/bin/cpp /lib

ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/$VERSION/liblto_plugin.so \
        /usr/lib/bfd-plugins/

mkdir -pv /usr/share/gdb/auto-load/usr/lib{,32}

mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib

# For multilib
# mv -v /usr/lib32/*gdb.py /usr/share/gdb/auto-load/usr/lib32

clear
echo -e "\e[1;32mТестирование работоспособности...\e[0m
ВНИМАНИЕ: используется замедление 0.5 сек."
echo 'int main(){}' > dummy.c
cc dummy.c -v -Wl,--verbose &> dummy.log
sleep 0.5
readelf -l a.out | grep ': /lib'
sleep 0.5

echo -e "\e[1mПроверка на соответствие стартовых файлов...\e[0m"
grep -o '/usr/lib.*/crt[1in].*succeeded' dummy.log
sleep 0.5

echo -e "\e[1mПроверка поиска компилятором нужных заголовочных файлов...\e[0m"
grep -B4 '^ /usr/include' dummy.log
sleep 0.5

echo -e "\e[1mПроверка поиска компилятором корректных путей поиска...\e[0m"
grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'
sleep 0.5

echo -e "\e[1mПроверка использования компилятором нужной стандартной библиотеки...\e[0m"
grep "/lib.*/libc.so.6 " dummy.log
sleep 0.5

echo -e "\e[1mПроверка использования компилятором нужного динамического компоновщика...\e[0m"
grep "found " dummy.log

rm -v dummy.c a.out dummy.log
