#!/bin/bash
set -Eeuo pipefail
# Build package libcap from port
# Port created by Linuxoid85
#
# (C) 2021 Michail [Linuxoid85] Krasnov <linuxoid85@gmail.com>

cd /usr/src

VERSION="2.60"

wget https://lx4u.ru/downloads/packages/libcap-$VERSION.tar.xz
tar -xf libcap-$VERSION.tar.xz
cd libcap-$VERSION

sed -i '/install -m.*STA/d' libcap/Makefile

make lib=lib
make lib=lib install
chmod -v 755 /lib/lib{cap,psx}.so.2

mv -v /lib/libpsx.a /usr/lib
rm -v /lib/libcap.so
ln -sfv ../../lib/libcap.so.2 /usr/lib/libcap.so
